# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MutiWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MutiWidget(object):
    def setupUi(self, MutiWidget):
        MutiWidget.setObjectName("MutiWidget")
        MutiWidget.resize(988, 799)
        self.scrollArea = QtWidgets.QScrollArea(MutiWidget)
        self.scrollArea.setGeometry(QtCore.QRect(0, 50, 451, 591))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 449, 589))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.CodeEditor = NewCodeEditor(self.scrollAreaWidgetContents)
        self.CodeEditor.setGeometry(QtCore.QRect(30, 0, 421, 591))
        self.CodeEditor.setObjectName("CodeEditor")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.detectWidget = QtWidgets.QTabWidget(MutiWidget)
        self.detectWidget.setGeometry(QtCore.QRect(470, 10, 511, 771))
        self.detectWidget.setObjectName("detectWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.detectWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.detectWidget.addTab(self.tab_4, "")
        self.horizontalLayoutWidget = QtWidgets.QWidget(MutiWidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 431, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pb_format = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pb_format.setObjectName("pb_format")
        self.horizontalLayout.addWidget(self.pb_format)
        self.pb_compile = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pb_compile.setObjectName("pb_compile")
        self.horizontalLayout.addWidget(self.pb_compile)
        self.pb_run = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pb_run.setObjectName("pb_run")
        self.horizontalLayout.addWidget(self.pb_run)
        self.pb_detect = detectMenuButton(self.horizontalLayoutWidget)
        self.pb_detect.setObjectName("pb_detect")
        self.horizontalLayout.addWidget(self.pb_detect)
        self.LogAndCmd = QtWidgets.QTabWidget(MutiWidget)
        self.LogAndCmd.setGeometry(QtCore.QRect(0, 660, 451, 121))
        self.LogAndCmd.setObjectName("LogAndCmd")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.tab)
        self.scrollArea_2.setGeometry(QtCore.QRect(0, 0, 441, 91))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 439, 89))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.te_log = QtWidgets.QTextEdit(self.scrollAreaWidgetContents_2)
        self.te_log.setGeometry(QtCore.QRect(0, 0, 441, 91))
        self.te_log.setObjectName("te_log")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.LogAndCmd.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.tab_2)
        self.scrollArea_3.setGeometry(QtCore.QRect(0, 0, 441, 91))
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 439, 89))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.te_cmd = CmdTextEdit(self.scrollAreaWidgetContents_3)
        self.te_cmd.setGeometry(QtCore.QRect(0, 0, 441, 87))
        self.te_cmd.setObjectName("te_cmd")
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.LogAndCmd.addTab(self.tab_2, "")

        self.retranslateUi(MutiWidget)
        self.detectWidget.setCurrentIndex(0)
        self.LogAndCmd.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MutiWidget)

    def retranslateUi(self, MutiWidget):
        _translate = QtCore.QCoreApplication.translate
        MutiWidget.setWindowTitle(_translate("MutiWidget", "Form"))
        self.detectWidget.setTabText(self.detectWidget.indexOf(self.tab_3), _translate("MutiWidget", "欢迎使用代码检测功能"))
        self.detectWidget.setTabText(self.detectWidget.indexOf(self.tab_4), _translate("MutiWidget", "Tab 2"))
        self.pb_format.setText(_translate("MutiWidget", "规范代码格式"))
        self.pb_compile.setText(_translate("MutiWidget", "编译"))
        self.pb_run.setText(_translate("MutiWidget", "运行"))
        self.pb_detect.setText(_translate("MutiWidget", "静态检测"))
        self.LogAndCmd.setTabText(self.LogAndCmd.indexOf(self.tab), _translate("MutiWidget", "Log Information"))
        self.LogAndCmd.setTabText(self.LogAndCmd.indexOf(self.tab_2), _translate("MutiWidget", "CMD"))
from UI.codeAudit.CmdTextEditor import CmdTextEdit
from UI.codeAudit.NewCodeEditor import NewCodeEditor
from UI.extentDetect.detectMenuButton import detectMenuButton
