# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FindDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(550, 300)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 60, 81, 16))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(330, 50, 101, 31))
        self.pushButton.setObjectName("pushButton")
        self.checkBox = QtWidgets.QCheckBox(Dialog)
        self.checkBox.setGeometry(QtCore.QRect(100, 100, 141, 19))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_2.setGeometry(QtCore.QRect(320, 100, 111, 19))
        self.checkBox_2.setObjectName("checkBox_2")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(100, 50, 221, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.pb_next = QtWidgets.QPushButton(Dialog)
        self.pb_next.setGeometry(QtCore.QRect(440, 50, 93, 31))
        self.pb_next.setObjectName("pb_next")
        self.number = QtWidgets.QLabel(Dialog)
        self.number.setGeometry(QtCore.QRect(250, 20, 72, 15))
        self.number.setText("")
        self.number.setObjectName("number")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "查找字符串："))
        self.pushButton.setText(_translate("Dialog", "查找全部"))
        self.checkBox.setText(_translate("Dialog", "支持正则表达式"))
        self.checkBox_2.setText(_translate("Dialog", "忽略大小写"))
        self.pb_next.setText(_translate("Dialog", "查找下一个"))
